# cargo-deny configuration for Solana Watchtower
# See https://embarkstudios.github.io/cargo-deny/

[graph]
targets = [
    "x86_64-unknown-linux-gnu",
]

[advisories]
# Security vulnerability database
vulnerability = "deny"
unmaintained = "warn"
unsound = "warn" 
yanked = "deny"

# Ignore known security issues from Solana ecosystem
ignore = [
    "RUSTSEC-2024-0344",  # curve25519-dalek timing variability
    "RUSTSEC-2022-0093",  # ed25519-dalek double public key signing oracle attack  
    "RUSTSEC-2025-0009",  # ring AES functions may panic
    "RUSTSEC-2025-0010",  # ring unmaintained versions
    "RUSTSEC-2021-0139",  # ansi_term unmaintained
    "RUSTSEC-2024-0375",  # atty unmaintained
    "RUSTSEC-2024-0388",  # derivative unmaintained
    "RUSTSEC-2024-0436",  # paste unmaintained
    "RUSTSEC-2021-0145",  # atty unsound
    "RUSTSEC-2023-0033",  # borsh unsound
]

[licenses]
# License policy - allow common open source licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]

# Confidence threshold for detecting a license from a file header/contents
confidence-threshold = 0.9
exceptions = []

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"

# List of crates that are allowed to have multiple versions
skip = [
    # Common crates that often have version conflicts
    "syn",
    "proc-macro2", 
    "quote",
    "serde",
    "serde_derive",
    "tokio",
    "futures",
]

# Skip certain crates altogether
skip-tree = []

[sources]
# Lint level for what to happen when a crate from a crate registry that is not in the allow list is encountered
unknown-registry = "warn"
unknown-git = "warn"

[sources.allow-registry]
# List of URLs for allowed crate registries
"https://github.com/rust-lang/crates.io-index" = true 